# Netlify configuration file

[build]
  # Directory to change to before starting a build
  base = ""
  
  # Build command - builds the client-side application
  command = "npm run build"
  
  # Directory that contains the deploy-ready files
  publish = "dist/public"
  
  # Node version for builds
  environment = { NODE_VERSION = "20" }

[build.environment]
  # Environment variables for build
  VITE_API_URL = "/"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
